sudo: required
services:
  - docker

before_install:
  - docker build -t hoacaphe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hoacaphe/react-test npm test -- --coverage

after_success:
  - docker build -t hoacaphe/multi-client ./client
  - docker build -t hoacaphe/multi-server ./server
  - docker build -t hoacaphe/multi-nginx ./nginx
  - docker build -t hoacaphe/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push hoacaphe/multi-client
  - docker push hoacaphe/multi-server
  - docker push hoacaphe/multi-nginx
  - docker push hoacaphe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-west-2-011436892268
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"